name: Rust + .NET Build

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '10.x.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build IPFD
        working-directory: ipfd
        run: |
          cargo build --release

      - name: Build plugin (No SMA)
        run: |
          dotnet build --configuration Release --nologo

      - name: Upload a Build Artifact (No SMA)
        uses: actions/upload-artifact@v4
        with:
          name: artifact-no-sma
          path: |
            ./Dynamis/bin/x64/Release/*

      - name: Build plugin (With SMA)
        run: |
          dotnet build --configuration ReleaseWithSMA --nologo

      - name: Upload a Build Artifact (With SMA)
        uses: actions/upload-artifact@v4
        with:
          name: artifact-with-sma
          path: |
            ./Dynamis/bin/x64/ReleaseWithSMA/*
